### ISSUE TITLE
Is it possible that I can use the data of servers not only in file?

### ISSUE THREAD

**Issue by KnightE** [RJ/ketama#2]
Hi, I use ketama(php) in my project. It's very helpful, and I like it so much!
In php client, the functions are simple and clear:
ketama_roll()
ketama_get_server()
ketama_destroy()

Well, my problem is, can I roll the data of servers not only in file?
I can control the data in db, mem and so on... If so, it will be more scalable.
The strategy using file does not fit the distribution system's requirement.

Sorry for my poor english. Thanks for the perfect tool again.

KnightE

**Comment by RJ** [comment]
Ketama only supports reading servers from the file at the moment.

Perhaps you could store the servers in the db, and use PHP to write the server file, based on data from the db.
